application: api-test-platform
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /img
  static_dir: application/static/img
- url: /fonts
  static_dir: application/static/fonts
- url: /js
  static_dir: application/static/js
- url: /css
  static_dir: application/static/css
- url: /font-awesome
  static_dir: application/static/font-awesome



- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
